### ISSUE TITLE
Some information is missing...

### ISSUE THREAD

**Issue by bigbigpark** [nobleo/xsens_mti_driver#11]
Hi, I found your repository fortunately. So I can build and run MTi driver successfully. <br/>
When I run `roslaunch xsens_mti_driver xsens_mti_node.launch` <br/> It gives me only quaternion measurements. <br/>
![image](https://user-images.githubusercontent.com/72936863/187631577-0047720d-71cf-4bfc-bbd6-20a32d0b3957.png)

How can I get angular_velocity and linear_acceleration with the quaternion ?

**Comment by MCFurry** [comment]
Unfortunately you need to configure that via mt_manager, which is in the XSens SDK.
The ROS node does not allow configuration of the device itself.

In the mt_manager application you can configure the sensor what data to output and thus also enable angular_velocity and linear_acceleration.

**Comment by bigbigpark** [comment]
As you mensioned I found how to change the configuration in the `mt manager`.
Thanks for your active replying!
