### ISSUE TITLE
where does the header timestamp come from?

### ISSUE THREAD

**Issue by jankin1024** [nobleo/xsens_mti_driver#9]
After running `roslaunch xsens_mti_driver xsens_mti_node.launch`, the header of msg in topic /imu/data contains the timestamp element. I wonder if it is generated when receiving raw data from xsens and building the new msg with a timestamp from `ros::Time::now`? Or does it set the msg header timestamp by the raw data's time(if it has, I just wondering) from the imu hardware clock?
Thanks very much. looking forward your reply~

**Comment by Timple** [comment]
As per README: 

> ROS timestamps The data messages from devices are time stamped on arrival in the ROS driver. When collecting data at higher rates, eg 100 Hz, the times between reads can differ from the configured output rate in the device. This is caused by possible buffering in the USB/FTDI driver.

> Work-around: for accurate and stable time stamp information, users can make use of the sensor reported time stamp (/imu/time_ref) instead.

**Comment by narutojxl** [comment]
Hello @jankin1024 and @Timple, 
Do you mean the timestamp of  output topic `/imu/data` is from the system driver running on ? In the [xsens mtmanager software](https://www.xsens.com/software-downloads),  about `Timestamp`,  Which configuration option should be marked with √ ? If we want the msg time is from the system driver running on, not from the imu sensor.  Thanks for your help very very much.

![Screenshot from 2022-03-03 15-21-55](https://user-images.githubusercontent.com/6205343/156516833-f700e120-f045-4389-957a-d322ef450076.png)

**Comment by Timple** [comment]
> Do you mean the timestamp of output topic /imu/data is from the system driver running on ?

That is what the README says:

> ROS timestamps The data messages from devices are time stamped on arrival in the ROS driver. 

I didn't check the code.

**Comment by narutojxl** [comment]
thanks author :)

**Comment by jankin1024** [comment]
You can find the code about 'timestamp' in [src/xdacallback.cpp#L65](https://github.com/nobleo/xsens_mti_driver/blob/a9f840bf42985e32b27c7bf9df4158ab0444bfab/src/xdacallback.cpp#L65).

I find that from 'imupublisher.h', and 'xdainterface.cpp#93' calls the imupublisher. We can also see that the message comes from `RosXsDaraPacket` in line76, go to the 'next' function, we will find how the data and timestamp are generated.

```cpp
// Returns empty packet on timeout
RosXsDataPacket XdaCallback::next(const std::chrono::milliseconds &timeout)
{
	RosXsDataPacket packet;

	std::unique_lock<std::mutex> lock(m_mutex);

	if (m_condition.wait_for(lock, timeout, [&] { return !m_buffer.empty(); }))
	{
		assert(!m_buffer.empty());

		packet = m_buffer.front();
		m_buffer.pop_front();
	}

	return packet;
}

void XdaCallback::onLiveDataAvailable(XsDevice *, const XsDataPacket *packet)
{
	std::unique_lock<std::mutex> lock(m_mutex);
	ros::Time now = ros::Time::now();

	assert(packet != 0);

	// Discard oldest packet if buffer full
	if (m_buffer.size() == m_maxBufferSize)
	{
		m_buffer.pop_front();
	}

	// Push new packet
	m_buffer.push_back(RosXsDataPacket(now, *packet));

	// Manual unlocking is done before notifying, to avoid waking up
	// the waiting thread only to block again
	lock.unlock();
	m_condition.notify_one();
}

```

I changed the line 68 with 
```cpp
ros::Time now.fromNsec(XsDataPacket_sampleTime64(packet));
```
I have a few memories about that.... It seems to return the current time from when the IMU starts to work, rather than when the IMU driver starts to work. 

Hope you will enjoy that. And write some here if you have new ideas.
Best and Thanks

**Comment by narutojxl** [comment]
@jankin1024,  thanks for your detailed and kind  reply very much :)

**Comment by narutojxl** [comment]
BTW, I have a MTi-G-710, when i see the `/imu/time_ref/time_ref` topic, [there is a jitter](https://base.xsens.com/s/question/0D50900001UrKOdCAN/ros-driver-of-some-topicss-timestamp?language=en_US), Is this phonomenon normal, thanks for your help.

**Comment by narutojxl** [comment]
BTW, I have a MTi-G-710, when i see the `/imu/time_ref/time_ref` topic, [there is a jitter](https://base.xsens.com/s/question/0D50900001UrKOdCAN/ros-driver-of-some-topicss-timestamp?language=en_US), Is this phonomenon normal, thanks for your help.
